services:
  - type: web
    name: ecom-saas-web
    env: docker
    plan: free

    envVars:
      - key: PORT
        value: "80"
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: LOG_CHANNEL
        value: errorlog
      - key: APP_KEY
        generateValue: true
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_URL
        fromDatabase:
          name: ecom-saas-db
          property: connectionString

databases:
  - name: ecom-saas-db
    plan: free
    databaseName: ecom_saas
    user: ecom_saas_user
